[versions]
agp = "8.4.0"
kotlin = "1.9.23"
coreKotlin = "1.13.1"
appcompat = "1.6.1"
material = "1.12.0"
constraintlayout = "2.1.4"
lifecycle = "2.7.0"
coroutines = "1.8.0"
socketio = "2.1.0"
zxing = "3.5.3"
zxingEmbedded = "4.3.0"
supabase = "2.6.1"
ktor = "2.3.11"
webrtc = "1.1.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKotlin" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
socket-io-client = { group = "io.socket", name = "socket.io-client", version.ref = "socketio" }
zxing-core = { group = "com.google.zxing", name = "core", version.ref = "zxing" }
supabase-realtime = { group = "io.github.jan-tennert.supabase", name = "realtime-kt", version.ref = "supabase" }
ktor-client-android = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }
stream-webrtc = { group = "io.getstream", name = "stream-webrtc-android", version.ref = "webrtc" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
